name: Test Wait for Main Build
on:
  workflow_dispatch:

jobs:
  wait-for-main-build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for main-build workflow to succeed
        uses: ezhang6811/wait-on-check-action@67978fbb1a5dd3bac64fe2fed0fe98574861f64e
        with:
          ref: ${{ github.ref }}
          check-name: 'dummy-build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          allowed-conclusions: success
